apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "vector-collection"
  rules:
    - actions: ["search"]
      effect: EFFECT_ALLOW
      roles:
        - retriever
      condition:
        match:
          expr: request.resource.attr.collection == "legal-docs"